# Generated by Django 5.0 on 2025-02-12 11:50

import apps.user.models
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=120, unique=True, verbose_name='Email')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Last Name')),
                ('is_active', models.BooleanField(default=False, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='Active')),
                ('is_admin', models.BooleanField(default=False, help_text='Designates whether the user should be treated as an employee/admin.', verbose_name='Employee')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='Backend Access')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning the models.', verbose_name='Superuser')),
                ('email_verified', models.BooleanField(default=False, verbose_name='Email Verified')),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to=apps.user.models.user_img_upload_location, verbose_name='Profile')),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=15, null=True, region=None, verbose_name='Phone Number')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Bio')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Last Login')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
