# Generated by Django 5.0 on 2025-02-18 10:49

import apps.project.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.project.models.comment_document_upload_location)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='project.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
